### ISSUE TITLE
Test revenu_net.yaml ne tourne plus

### ISSUE THREAD

**Issue by leaamb** [openfisca/openfisca-mali#10]
@benjello  J'ai voulu montrer ce qu'on avait fait jeudi à Anne-Sophie, et je suis incapable de refaire tourner le test revenu_net.yaml sur VSCode.

J'obtiens ce message d'erreur : "WARNING:openfisca_core.scripts:Several country packages detected : `openfisca_senegal, openfisca_mali`. Using `openfisca_senegal` by default. To use another package, please use the --country-package option."

Et à la fin j'ai : "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Léa\\Documents\\DIAL\\OpenFisca\\openfisca-mali\\openfisca_mali\\revenu_net.yaml'"

J'ai pensé que c'était du à une erreur de directory, mais lorsque je le change pour qu'il soit plus précis j'obtiens cette erreur : "ERROR: b'C:\\Users\\L\xc3\xa9a\\Documents\\DIAL\\OpenFisca\\openfisca-mali\\openfisca_mali\\tests\\revenu_net.yaml is not a valid OpenFisca test file'"

Donc je suis un peu perdue.

Si tu préfères voir le problème sur mon ordi direct, je peux passer dans le semaine !

**Comment by benjello** [comment]
Il faut préciser le pays quand on en a plusieurs pays installé:
```shell
openfisca-run-test -c openfisca_mali openfisca_mali/tests/
```

**Comment by benjello** [comment]
Je te laisse me relancer si cela ne résout pas ton problème.

**Comment by benjello** [comment]
Sinon n'hésite pas à fermer.

**Comment by leaamb** [comment]
C'est bon, merci !
