### ISSUE TITLE
Renseigner le wiki - mali

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-mali#3]
Afin de cerner l'ensemble des éléments du système socio-fiscal malien à mettre en oeuvre dans openfisca, il est utile de disposer d'une description sommaire des différentes composantes de ce système avec des liens vers des sources appropriées.

Il serait donc très utile de rassembler cette information dans le [wiki](https://github.com/openfisca/openfisca-mali/wiki).

@leaamb l'idéal serait que tu reportes brièvement dans le wiki les éléments de législation que tu as rassemblés. Puis dans un second mouvement, nous les mettrons sous forme de code openfisca étape par étape.

**Comment by benjello** [comment]
@leaamb : je me suis permis de corriger le lien sur la page Home.

**Comment by benjello** [comment]
@leaamb : essaie de présenter le système de la façon la plus hiérarchisée possible afin qu'un lecteur puisse aller rapidement à l'information qui l'intéresse en parcourant les grandes sections puis les plus petites.

Typiquement, on ira chercher de quoi est composée une base imposable, quels abattements  s'appliquent etc. Donc n'hésite pas non plus à abuser de liste et d'énumération. Cela se lit plus vite notamment sur un écran d'ordinateur.

**Comment by benjello** [comment]
@leaamb : me suis permis d'éditer pour rendre mon propos plus clair.

**Comment by benjello** [comment]
@leaamb : je vois que tu signales que certaines variables essentielles pour calculer certains impôts ne sont pas disponible dans l'enquête. Il vaux en effet mieux se concentrer sur ce qui sera utile à modéliser.
Il serait peut-être utile de lister les variables de revenus, consommation, et de patrimoine disponibles dans l'enquête.

**Comment by leaamb** [comment]
@benjello : C'est un document qui existe déjà. Est-ce qu'il y' a moyen de lier des documents (pdf ou excel) au projet sur Github, ou bien il faut que j'en recrée une version quelque part ? Dans ce cas, dans le wiki je suppose ?

**Comment by benjello** [comment]
@leaamb : tu peux créer un répertoire assets dans ce repo ou tu mettrais ces fichiers. Attention ils seront désormais publics (visibles par tout le monde).
Evite si possible le format excel qui n'est pas visible depuis github ou un éditeur car c'est un format binaire. Le transformer en csv si possible.

**Comment by benjello** [comment]
Je ferme car on a désormais une Roadmap.
